### ISSUE TITLE
AttributeValue unmarshalling Example

### ISSUE THREAD

**Issue by ezeql** [eawsy/aws-lambda-go-event#2]
Is it possible to unmarshall an AttributeValue into a proper structure?
ref: https://godoc.org/github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute

**Comment by fsenart** [comment]
Hi @ezeql,

At the beginning we've made the choice to not depend on the AWS SDK in order to keep the project lightweight and self contained. So, there is no immediate solution to unmarshal the attribute value to a structure.
I think we should reconsider our first choice in order to provide more useful events. Otherwise we have to copy/past the same decoders than the official SDK in the project, and it is not a viable choice. 
Do you have any other proposition?

**Comment by ezeql** [comment]
hi @fsenart,

I Agree relying on the official SDK is the way to go.  It would be cool to not to depend on it but, as you said, copy pasta from an official project doesn't worth the time.

 Thanks for looking at this!
